article_content_task:
  description: >
    Erstelle eine freundliche, sachliche und erklärende
    Produktbeschreibung für folgendes Kleidungsstück:
    - **Produktname:** {Produktname}
    - **Material:** {Material}
    
    Die Beschreibung soll zwischen 75 und 125 Wörtern lang
    sein und die Temperature_Empfehlung beinhalten.
  expected_output: >
    Eine verständliche und ansprechende Produktbeschreibung in deutscher Sprache,
    die alle genannten Produkteigenschaften enthält und zwischen 75 und 125 Wörtern lang ist.
    Der Text soll in einem zusammenhängenden Absatz formatiert sein.
  agent: article_content_writer

also_asked_task:
  description: >
    Finde die fünf häufigsten Fragen heraus, welche die Nutzer stellen und welche 
    Themen sie interessieren im Zusammenhang mit dem Produkt.
  expected_output: >
    Eine Liste von Fragen und Themen, die die Nutzer häufiger stellen und interessieren.
  agent: also_asked_researcher

also_asked_answerer_task:
  description: >
    Antworte auf die Fragen, die die Nutzer häufiger stellen.
  expected_output: >
    Die Produktbeschreibung und eine Liste von Fragen und Antworten.
  agent: also_asked_answerer

    # - **Material:** {Material}
    # - **Strickart:** {Strickart}
    # - **Maschendichte:** {Maschendichte} Gauge (bitte ausgeschrieben
    # angeben)
    # - **Garnfeinheit (Ne-Wert):** {Garnfeinheit}
    # - **Passform:** {Passform}
    # - **Farbe:** {Farbe}

