article_content_task:
  description: >
    Erstelle eine freundliche, sachliche und erklärende
    Produktbeschreibung für folgendes Kleidungsstück:
    - **Produktname:** {Produktname}
    - **Material:** {Material}
    - **Strickart:** {Strickart}
    - **Maschendichte:** {Maschendichte} Gauge (bitte ausgeschrieben
    angeben)
    - **Garnfeinheit (Ne-Wert):** {Garnfeinheit}
    - **Passform:** {Passform}
    - **Farbe:** {Farbe}

    Die Beschreibung soll zwischen 75 und 125 Wörtern lang
    sein. 
  expected_output: >
    Eine verständliche und ansprechende Produktbeschreibung in deutscher Sprache,
    die alle genannten Produkteigenschaften enthält und zwischen 75 und 125 Wörtern lang ist.
    Der Text soll in einem zusammenhängenden Absatz formatiert sein.
  agent: article_content_writer

# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
